package com.BoostingWebsite.configuration.security;

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer;

class SecurityWebApplicationInitializer extends AbstractSecurityWebApplicationInitializer {
}
